name: Unit Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Setup up API key
        env:
          MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
        run: echo MAPS_API_KEY="$MAPS_API_KEY" > ./local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit tests with gradlew
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew jacocoTestReport connectedCheck

      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov --dir ./app/build/test-results/testDebugUniTest/
