name: Documentation

on:
  push:
    branches: [ "master" , "push-action/**"]

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup up API key
        env:
          MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
        run: echo MAPS_API_KEY="$MAPS_API_KEY" > ./local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate docs
        run: |
          ./gradlew dokkaHtml
          mv ./app/build/dokka/html ./docs

      - name: Commit Changes
        run: |
          git add --all
          git commit -m "[BOT] documentation"

      - name: Push Changes
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          branch: master
          unprotected_views: true